// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4-ptvqA2wiZGPLhYyWzGvnZStbLsq-kc',
    appId: '1:280957782862:web:678bbdaaf4f747960aec1f',
    messagingSenderId: '280957782862',
    projectId: 'template-fa247',
    authDomain: 'template-fa247.firebaseapp.com',
    storageBucket: 'template-fa247.appspot.com',
    measurementId: 'G-ZQLJC2C67R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVi3m8zgYPy-EkDIrxq2C7-WvXEUrXiY',
    appId: '1:280957782862:android:8befd6f0dd0e17390aec1f',
    messagingSenderId: '280957782862',
    projectId: 'template-fa247',
    storageBucket: 'template-fa247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf9l8nlZdW1OPEGpPlDDrr0q4YnkxkfS0',
    appId: '1:280957782862:ios:4a978d5e2c23bdbd0aec1f',
    messagingSenderId: '280957782862',
    projectId: 'template-fa247',
    storageBucket: 'template-fa247.appspot.com',
    iosClientId: '280957782862-nl5b6er6egkkmbrk2ehqnmucartl9ivi.apps.googleusercontent.com',
    iosBundleId: 'com.nomisal.tempt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf9l8nlZdW1OPEGpPlDDrr0q4YnkxkfS0',
    appId: '1:280957782862:ios:d01591a4dc85598b0aec1f',
    messagingSenderId: '280957782862',
    projectId: 'template-fa247',
    storageBucket: 'template-fa247.appspot.com',
    iosClientId: '280957782862-i8ri8rfki6vk9j942fgcas5evse1dogc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempt',
  );
}
